Devops/ci
meateam/file-service pull request #228
Opened 2020-12-20 12:50 UTC by yosef32

fix jenkinsfile

2020-12-21 21:04 UTC, Shahar-Y requested changes

2020-12-21 21:04 UTC, Shahar-Y commented on src/file/file.service.spec.ts
> -    });
Why was the test deleted?

2020-12-24 09:22 UTC, yosef32 commented on src/file/file.service.spec.ts
> -    });
done

2020-12-24 10:17 UTC, Shahar-Y approved these changes

2020-12-24 10:17 UTC, merged